### ISSUE TITLE
System configurations

### ISSUE THREAD

**Issue by abhishekkritarth** [DongjunLee/conversation-tensorflow#6]
HI Dongjunlee,
    I am using a  CPU system with 8 GB RAM for training, and i used cornell-movie-dialogues.yml configuration file, only 5000 training steps are completed since 5 days. 

Can you please tell me your system configuration which you used for training and how much time taken for training of 1 lakh training  steps.

Thanks in advance

**Comment by DongjunLee** [comment]
Hi @abhishekkritarth,
You must use GPU.

For check_tiny, CPU is allright.
But, in cornell-movie-dialog, there are lots of data and the models are complex.

I am using 2 NVIDIA Tesla P100 GPUs (16GB) and It takes 3 days to train for 100000 steps.

**Comment by abhishekkritarth** [comment]
Thanks @DongjunLee
